version: "3"
services:
  redinsight:
   image: dockereg/component-prometheus:${VERSION}
   container_name: prometheus
   volumes:
     - /opt/prometheus/:/etc/prometheus/
   command:
     - '--config.file=/etc/prometheus/prometheus.yml'
   ports:
     - 9090:9090
